### ISSUE TITLE
Descending sort

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/sort-on#10]
Would be useful to be able to sort descending too.

I'm thinking a syntax like:

```js
sortOn([{x: 'c', y: 'c'}, {x: 'b', y: 'a'}, {x: 'b', y: 'b'}], ['-x', 'y']);
// sorts `x` descending
```

**Comment by stevemao** [comment]
I like it :+1:

**Comment by kevva** [comment]
Yeah, currently I'm doing `sortOn(arr, prop).reverse()`, but would definitely be better to do it here.

**Comment by sindresorhus** [comment]
@kevva Yup, but that won't work correctly with muliple sort properties with different sorting directions like the above example.

**Comment by kevva** [comment]
How would this look with functions and dot props?

**Comment by sindresorhus** [comment]
> How would this look with functions and dot props?

For dot props it would be the same `-x.y`. For functions I'm not really sure.

> And what if you have a key named -- or whatever? 

I've never seen that before, but as with `dot-prop`, we could allow escaping in that edge-case.

> I'd rather use opts.order/opts.sort/opts.desc or whatever to avoid edge cases.

That would indeed be simpler, but would not enable different sorting between props as seen in my issue description.

**Comment by kevva** [comment]
> That would indeed be simpler, but would not enable different sorting between props as seen in my issue description.

Oh, that's a good point. Alright, I think this is worth a PR from me then :).
