### ISSUE TITLE
After sorting, empty strings are at the beginning of the sorted array

### ISSUE THREAD

**Issue by VladShcherbin** [sindresorhus/sort-on#14]
```js
const array = [
  { title: 'b' },
  { title: '' },
  { title: 'a' }
]

console.log(sortOn(array, ['title']))
```

Output:

```js
[
  { title: '' },
  { title: 'a' },
  { title: 'b' }
]
```

Expected output:

Since it's sorting by string, I'd expect empty strings to be last in the array:

```js
[
  { title: 'a' },
  { title: 'b' },
  { title: '' }
]
```

**Comment by kevva** [comment]
I agree :+1:. PR welcome (would probably be added along with the `null` checks).

**Comment by Ricardo-Silva91** [comment]
Hello, I made a pull request with a proposed solution for this issue (#15).
Feedback is welcome 😄
